# Generated by Django 5.1.7 on 2025-04-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
