# Generated by Django 5.1.7 on 2025-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='delete_by',
            new_name='deleted_by',
        ),
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
