# Generated by Django 5.1.6 on 2025-03-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_company_companies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table='companies',
        ),
    ]
