# Generated by Django 5.1.7 on 2025-04-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_delete_by_companies_deleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='deleted_by',
            new_name='deletedBy',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='updated_by',
            new_name='updatedBy',
        ),
    ]
