# Generated by Django 5.1.6 on 2025-04-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='deleted_at',
            new_name='deletedAt',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
