# Generated by Django 5.1.7 on 2025-04-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(blank=True, help_text="Object containing creator details, e.g., {'_id': ObjectID, 'email': string}", null=True)),
                ('updated_by', models.JSONField(blank=True, help_text="Object containing updater details, e.g., {'_id': ObjectID, 'email': string}", null=True)),
                ('deleted_by', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='permissions.permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx'), models.Index(fields=['is_deleted'], name='roles_is_dele_20cf43_idx')],
            },
        ),
    ]
