# Generated by Django 5.1.6 on 2025-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('roles', '0002_alter_roles_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='permissions.permissions'),
        ),
    ]
