# Generated by Django 5.1.7 on 2025-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.JSONField(blank=True, help_text="Object containing creator details, e.g., {'_id': ObjectID, 'email': string}", null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_by',
            field=models.JSONField(blank=True, help_text="Object containing updater details, e.g., {'_id': ObjectID, 'email': string}", null=True),
        ),
    ]
