# Generated by Django 5.1.6 on 2025-04-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='company',
            new_name='companyId',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='deleted_at',
            new_name='deletedAt',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='job',
            new_name='jobId',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='user_id',
            new_name='userId',
        ),
    ]
