# Generated by Django 5.1.6 on 2025-03-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='job_id',
            new_name='job',
        ),
    ]
