# Generated by Django 5.1.6 on 2025-03-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_company_id_resume_company_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='resume',
        ),
    ]
