# Generated by Django 5.1.6 on 2025-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_company_resume_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
