# Generated by Django 5.1.7 on 2025-04-10 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_resume_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='deletedAt',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='createdBy',
            new_name='deleted_by',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='delete_by',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='userId',
        ),
        migrations.AddField(
            model_name='resume',
            name='created_by',
            field=models.JSONField(blank=True, help_text="Object containing creator details, e.g., {'_id': ObjectID, 'email': string}", null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='updated_by',
            field=models.JSONField(blank=True, help_text="Object containing updater details, e.g., {'_id': ObjectID, 'email': string}", null=True),
        ),
    ]
