# Generated by Django 5.1.6 on 2025-03-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.JSONField(blank=True, help_text="Object containing creator details, e.g., {'_id': ObjectID, 'email': string}", null=True)),
                ('updated_by', models.JSONField(blank=True, help_text="Object containing updater details, e.g., {'_id': ObjectID, 'email': string}", null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Reference to the associated company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
