# Generated by Django 5.1.7 on 2025-03-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_id_user__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
    ]
