# Generated by Django 5.1.7 on 2025-03-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
